apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gkni25v5n-python
  janus-idp.io/tekton: gkni25v5n-python
  backstage.io/kubernetes-id: gkni25v5n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gkni25v5n-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
